export const AdminAction = {
  APPROVE_COMPANY: 'APPROVE_COMPANY',
  REJECT_COMPANY: 'REJECT_COMPANY',
  APPROVE_JOB: 'APPROVE_JOB',
  REJECT_JOB: 'REJECT_JOB',
  BAN_JOB: 'BAN_JOB',
  UNBAN_JOB: 'UNBAN_JOB',
  BAN_USER: 'BAN_USER',
  UNBAN_USER: 'UNBAN_USER',
  UPDATE_MASTER_DATA: 'UPDATE_MASTER_DATA',
  UPDATE_SERVICE_PACKAGE: 'UPDATE_SERVICE_PACKAGE',
  UPDATE_CV_TEMPLATE: 'UPDATE_CV_TEMPLATE',
  VIEW_PAYMENT_ORDER: 'VIEW_PAYMENT_ORDER',
  RETRY_PAYMENT_WEBHOOK: 'RETRY_PAYMENT_WEBHOOK',
  VIEW_AI_REVIEW_LOG: 'VIEW_AI_REVIEW_LOG'
};

export const AdminTargetType = {
  USER: 'USER',
  COMPANY: 'COMPANY',
  JOB: 'JOB',
  CV_TEMPLATE: 'CV_TEMPLATE',
  CV_SECTION: 'CV_SECTION',
  MASTER_DATA: 'MASTER_DATA',
  SERVICE_PACKAGE: 'SERVICE_PACKAGE',
  TRANSACTION: 'TRANSACTION',
  PAYMENT_ORDER: 'PAYMENT_ORDER',
  AI_CV_REVIEW: 'AI_CV_REVIEW'
};
