export const NotificationTypeCode = {
  EMPLOYER_VIEWED_CV: 'EMPLOYER_VIEWED_CV',
  NEW_CV_TEMPLATE: 'NEW_CV_TEMPLATE',
  MATCHING_JOB: 'MATCHING_JOB',
  INTERVIEW_INVITATION: 'INTERVIEW_INVITATION',
  APPLICATION_RESULT: 'APPLICATION_RESULT',
  COMPANY_VERIFIED: 'COMPANY_VERIFIED',
  COMPANY_REJECTED: 'COMPANY_REJECTED',
  JOB_APPROVED: 'JOB_APPROVED',
  JOB_REJECTED: 'JOB_REJECTED',
  JOB_BANNED: 'JOB_BANNED',
  WALLET_DEPOSIT_SUCCESS: 'WALLET_DEPOSIT_SUCCESS',
  PACKAGE_PURCHASE_SUCCESS: 'PACKAGE_PURCHASE_SUCCESS',
  PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_CANCELLED: 'PAYMENT_CANCELLED',
  AI_CV_REVIEW_COMPLETED: 'AI_CV_REVIEW_COMPLETED',
  AI_CV_REVIEW_FAILED: 'AI_CV_REVIEW_FAILED',
  AI_CV_REVIEW_QUOTA_EXCEEDED: 'AI_CV_REVIEW_QUOTA_EXCEEDED',
  SYSTEM_UPDATE: 'SYSTEM_UPDATE'
};

export const NotificationChannel = {
  IN_APP: 'IN_APP',
  EMAIL: 'EMAIL'
};

export const NotificationStatus = {
  UNREAD: 'UNREAD',
  READ: 'READ'
};

export const EmailDeliveryStatus = {
  NOT_REQUIRED: 'NOT_REQUIRED',
  PENDING: 'PENDING',
  SENT: 'SENT',
  FAILED: 'FAILED'
};

export const EmailProvider = {
  NODEMAILER: 'NODEMAILER',
  SENDGRID: 'SENDGRID',
  MAILGUN: 'MAILGUN',
  AMAZON_SES: 'AMAZON_SES'
};
